Update address_book(note).py
illarionovam/project-qwerty78 pull request #11
Opened 2023-12-19 18:14 UTC by 29Olesia

2023-12-19 19:49 UTC, illarionovam requested changes

2023-12-19 19:49 UTC, illarionovam commented on project_qwerty78/address_book.py
> +class Note:
клас note знаходиться у окремому модулі note.py
треба перенести конструктор туди

2023-12-19 19:49 UTC, illarionovam commented on project_qwerty78/address_book.py
> +        self.title = title
title - треба ініціалізувати черерз конструктор класу title
аналогічно контент (все знаходиться у модулі note.py)

2023-12-19 19:49 UTC, illarionovam commented on project_qwerty78/address_book.py
> +    def add_note(self, title, content):
я прибрала тут wrap_exception, бо він його треба викликати у зовнішніх функціях класу bot_utility
так само треба визначити констранти для команд і прописати їхні виклики у process_command методі
також зробити методи однойменні у класі bot_utility, які вже огорнути wrap_exception і кидати IndexError там, якщо index < 0 або >= len(notes)
чому не підходить просто спіймати ексепшн, як у початковій реалізації?
бо можна передати -1, це валідний індекс останньої нотатки, а ми таке не повинні приймати

2023-12-19 19:49 UTC, illarionovam commented on project_qwerty78/address_book.py
> +    def delete_note_by_index(self, index):
варто зазначити, що ноутс у нас мають індекси в системі з 0
а виводити ми будемо user-friendly з 1
тобто обробити на вході індекс і зменшити його на одиничку, а вже потім перевіряти його у діапазоні від 0 до довжини масиву

2023-12-19 19:49 UTC, illarionovam commented on project_qwerty78/address_book.py
> +    def edit_note_by_index(self, index, title, content):
краще розділити edit_note_by_index на апдейт тайтл та апдейт контент, як зроблено для контактів з апдейт день народження тощо

2023-12-19 19:49 UTC, illarionovam commented on project_qwerty78/address_book.py
> +    def add_note(self, title, content):
при створенні нотатки варто перевірити, що контент не пустий, а ось тайтл можливий пустим
модна глянути, як реалізовано add-contact функція, там name обовʼязкове поле
так як у нас нема унікальності нотаток, то дублі можуть бути на відміну від контактів

2023-12-20 09:04 UTC, illarionovam commented on project_qwerty78/address_book.py
> +        self.notes.append(Note(content, title))
тут краще зробити за аналогією з контактом, тобто конструктор викликається у bot_utility , а у функцію add додається вже готовий об'єкт Note

2023-12-20 15:25 UTC, 29Olesia commented on project_qwerty78/address_book.py
> +        self.notes.append(Note(content, title))
def add_note(self, note):
    self.notes.append(note)

2023-12-20 15:25 UTC, 29Olesia commented on project_qwerty78/address_book.py
> +    def delete_note_by_index(self, index):
def delete_note_by_index(self, index):
    adjusted_index = index - 1
    if 0 <= adjusted_index < len(self.notes):
        del self.notes[adjusted_index]
        return f"Нотатку з індексом {index} було видалено."
    else:
        return "Невірний індекс. Нотатку не знайдено."

2023-12-20 15:25 UTC, 29Olesia commented on project_qwerty78/address_book.py
> +    def edit_note_by_index(self, index, title, content):
def update_note_title_by_index(self, index, new_title):
    adjusted_index = index - 1
    if 0 <= adjusted_index < len(self.notes):
        self.notes[adjusted_index].title = new_title
        return f"Заголовок нотатки за індексом {index} оновлено."
    else:
        return "Невірний індекс. Нотатку не знайдено."

def update_note_content_by_index(self, index, new_content):
    adjusted_index = index - 1
    if 0 <= adjusted_index < len(self.notes):
        self.notes[adjusted_index].content = new_content
        return f"Вміст нотатки за індексом {index} було оновлено."
    else:
        return "Невірний індекс. Нотатку не знайдено."

2023-12-20 15:27 UTC, illarionovam commented on project_qwerty78/address_book.py
> +    def delete_note_by_index(self, index):
так, це воно)
перевірку індекса ми винесемо у клас bot_utility, а все інше - правильно)

2023-12-20 15:28 UTC, illarionovam commented on project_qwerty78/address_book.py
> +    def edit_note_by_index(self, index, title, content):
тут аналогічно, винесемо перевірку індекса у клас виклику, а сама реалізація правильна

2023-12-20 15:29 UTC, illarionovam commented on project_qwerty78/address_book.py
> +        self.notes.append(Note(content, title))
так, воно

тепер це все треба пушнути новим комітом)

2023-12-21 13:46 UTC, closed without merging