tags-addind-and-validation
illarionovam/project-qwerty78 pull request #33
Opened 2023-12-20 21:59 UTC by Vasyl-Gumeniuk

Adding tags by note name and validating tags has been implemented.

2023-12-20 22:44 UTC, illarionovam requested changes

2023-12-20 22:44 UTC, illarionovam commented on project_qwerty78/bot_utility.py
> +        raise exceptions.IncorrectArgsException("Incorrect format. Try [add-tag] [note_title] [tag]")
виправ, будь ласка, на шаблоний ексепшн, типу:
"Incorrect command format. Try " + constants.COMMAND_TO_COMMAND_FORMAT_MAP[constants.ADD_TAG_COMMAND])

аналогічно для ремув тега

2023-12-20 22:44 UTC, illarionovam commented on project_qwerty78/constants.py
> +    ADD_TAG_COMMAND: ADD_TAG_COMMAND + " \[note_title] \[tag]",
з тайлом легше помилитися, зробити опечатку, на мій погляд, краще робити додавання і видалення тегів по індексу, але готова до обговорення

2023-12-20 22:44 UTC, illarionovam commented on project_qwerty78/bot_utility.py
> +        raise exceptions.IncorrectArgsException("Incorrect format. Try [add-tag] [note_title] [tag]")
це не придираюся, якщо що, просто команд формат мапа містить екрановані [, а ти не екрануєш у команді
а також якщо захочемо перейменувати саме команду, то треба буде в декількох місцях виправляти, а не в олдному

2023-12-20 22:44 UTC, illarionovam commented on project_qwerty78/bot_utility.py
> +    matched_notes, _ = book.find_notes(note_title, search_by="title")
чому також краще пошук по індексу - по індексу завжди повернеться 1 рекорд
якщо ти задаш патер title
а в тебе буде два ноутс, один з заголовком title1, а другий з заголовком title2, то тобі повернеться масив і ти прибереш чи додаш тег лише на першу нотатку, що повернеться
тому голосую за пошуком за індексом (якщо що, його швидко реалізувати дуже)

2023-12-20 22:44 UTC, illarionovam commented on project_qwerty78/bot_utility.py
> +        return remove_tag_from_note(args, book)
давай додамо ще одну комнаду
remove-tags [index], аналогічну remove-phones [name] у контактах, яка за раз видалить усі теги - це зручно для користувача

2023-12-21 07:23 UTC, Vasyl-Gumeniuk commented on project_qwerty78/bot_utility.py
> +        raise exceptions.IncorrectArgsException("Incorrect format. Try [add-tag] [note_title] [tag]")
прийнято)

2023-12-21 07:23 UTC, Vasyl-Gumeniuk commented on project_qwerty78/constants.py
> +    ADD_TAG_COMMAND: ADD_TAG_COMMAND + " \[note_title] \[tag]",
прийнято)

2023-12-21 09:59 UTC, Vasyl-Gumeniuk commented on project_qwerty78/bot_utility.py
> +        return remove_tag_from_note(args, book)
Додано

2023-12-21 10:14 UTC, illarionovam requested changes

2023-12-21 10:14 UTC, illarionovam commented on project_qwerty78/bot_utility.py
> +        note_index = int(args[0]) - 1   #Check for valid integer and integer no less 0
у класі address_book зʼявилася зручна функція перевірки й адаптації індекса:
index = book.prepare_index(args[0])

у такому разі не потрібно дублювати з фукнкції у функцію по 6 рядків

2023-12-21 10:14 UTC, illarionovam commented on project_qwerty78/bot_utility.py
> +        raise exceptions.NoRecordException(f"No note found with index '{note_index + 1}'. Index is out of range.")
перевірки на noRecord не потрібні, бо індекс перевіряється у діапазоні від 0 до довжини масива
томі до сбди вно не дійде навіть)

2023-12-21 10:14 UTC, illarionovam commented on project_qwerty78/note.py
> +        return re.fullmatch(r'[A-Za-z0-9]{1,10}', tag) is not None and ' ' not in tag
перевірка на пробіл не потрібно, бо тут не match, а fullmatch

2023-12-21 10:14 UTC, illarionovam commented on project_qwerty78/note.py
> +        return re.fullmatch(r'[A-Za-z0-9]{1,10}', tag) is not None and ' ' not in tag
також пробіла по середині і по боках не може бути, бо ти приймаєш лише 2 аргументи у функції, а парс інпут робить це самостійно)

2023-12-21 10:14 UTC, illarionovam commented on project_qwerty78/bot_utility.py
> +        return str(e)   # Displaying an error message
не потрібно тут ловити цей ексепшн, wrap_exception декоратор зробить це самостійно
тобто трай-ексепт не потрібен взагалі)

2023-12-21 13:01 UTC, illarionovam requested changes

2023-12-21 13:01 UTC, illarionovam commented on project_qwerty78/bot_utility.py
>          note_var = book.notes[note_index]
цей try не потрібен, сюди не може попасти невалідний індекс

2023-12-21 13:01 UTC, illarionovam commented on project_qwerty78/bot_utility.py
> +        if not note_var.tags:
так само вважаю, що перевірка не потрібна, якщо нема що видаляти, просто покажемо, removed all tags і це не буде неправдою)

2023-12-21 13:01 UTC, illarionovam commented on project_qwerty78/bot_utility.py
> +    except IndexError:
не може бути indexError, якщо він вже підготований функцією, тому це зайвий трай кетч

2023-12-21 13:06 UTC, illarionovam approved these changes

2023-12-21 13:21 UTC, merged